  ItemSettings:Apply(neutrals.tiers, 1, 1, 'item_broom_handle');
  ItemSettings:Apply(neutrals.tiers, 1, 1, 'item_faded_broach');
  ItemSettings:Apply(neutrals.tiers, 1, 1, 'item_iron_talon');
  ItemSettings:Apply(neutrals.tiers, 1, 1, 'item_keen_optic');
  --ItemSettings:Apply(neutrals.tiers, 1, 1, 'item_mango_tree');
  ItemSettings:Apply(neutrals.tiers, 1, 1, 'item_ocean_heart');
  ItemSettings:Apply(neutrals.tiers, 1, 1, 'item_poor_mans_shield');
  ItemSettings:Apply(neutrals.tiers, 1, 1, 'item_royal_jelly');
  --ItemSettings:Apply(neutrals.tiers, 1, 1, 'item_trusty_shovel');
  ItemSettings:Apply(neutrals.tiers, 1, 1, 'item_recipe_ironwood_tree');
  -- Tier 1 Mid
  ItemSettings:Apply(neutrals.tiers, 1, 2, 'item_arcane_ring');
  ItemSettings:Apply(neutrals.tiers, 1, 2, 'item_broom_handle');
  ItemSettings:Apply(neutrals.tiers, 1, 2, 'item_faded_broach');
  ItemSettings:Apply(neutrals.tiers, 1, 2, 'item_iron_talon');
  ItemSettings:Apply(neutrals.tiers, 1, 2, 'item_keen_optic');
  --ItemSettings:Apply(neutrals.tiers, 1, 2, 'item_mango_tree');
  ItemSettings:Apply(neutrals.tiers, 1, 2, 'item_ocean_heart');
  ItemSettings:Apply(neutrals.tiers, 1, 2, 'item_poor_mans_shield');
  ItemSettings:Apply(neutrals.tiers, 1, 2, 'item_royal_jelly');
  --ItemSettings:Apply(neutrals.tiers, 1, 2, 'item_trusty_shovel');
  ItemSettings:Apply(neutrals.tiers, 1, 2, 'item_recipe_ironwood_tree');  
  -- Tier 1 Offlane
  ItemSettings:Apply(neutrals.tiers, 1, 3, 'item_arcane_ring');
  ItemSettings:Apply(neutrals.tiers, 1, 3, 'item_broom_handle');
  ItemSettings:Apply(neutrals.tiers, 1, 3, 'item_faded_broach');
  --ItemSettings:Apply(neutrals.tiers, 1, 3, 'item_iron_talon');
  ItemSettings:Apply(neutrals.tiers, 1, 3, 'item_keen_optic');
  --ItemSettings:Apply(neutrals.tiers, 1, 3, 'item_mango_tree');
  ItemSettings:Apply(neutrals.tiers, 1, 3, 'item_ocean_heart');
  ItemSettings:Apply(neutrals.tiers, 1, 3, 'item_poor_mans_shield');
  ItemSettings:Apply(neutrals.tiers, 1, 3, 'item_royal_jelly');
  --ItemSettings:Apply(neutrals.tiers, 1, 3, 'item_trusty_shovel');
  ItemSettings:Apply(neutrals.tiers, 1, 3, 'item_recipe_ironwood_tree');    
  -- Tier 1 Soft Support
  ItemSettings:Apply(neutrals.tiers, 1,4, 'item_arcane_ring');
  --ItemSettings:Apply(neutrals.tiers, 1,4, 'item_broom_handle');
  ItemSettings:Apply(neutrals.tiers, 1,4, 'item_faded_broach');
  --ItemSettings:Apply(neutrals.tiers, 1,4, 'item_iron_talon');
  ItemSettings:Apply(neutrals.tiers, 1,4, 'item_keen_optic');
  --ItemSettings:Apply(neutrals.tiers, 1,4, 'item_mango_tree');
  ItemSettings:Apply(neutrals.tiers, 1,4, 'item_ocean_heart');
  --ItemSettings:Apply(neutrals.tiers, 1,4, 'item_poor_mans_shield');
  ItemSettings:Apply(neutrals.tiers, 1,4, 'item_royal_jelly');
  ItemSettings:Apply(neutrals.tiers, 1,4, 'item_trusty_shovel');
  ItemSettings:Apply(neutrals.tiers, 1,4, 'item_recipe_ironwood_tree');      
  -- Tier 1 Hard Support
  ItemSettings:Apply(neutrals.tiers, 1, 5, 'item_arcane_ring');
  --ItemSettings:Apply(neutrals.tiers, 1, 5, 'item_broom_handle');
  ItemSettings:Apply(neutrals.tiers, 1, 5, 'item_faded_broach');
  --ItemSettings:Apply(neutrals.tiers, 1, 5, 'item_iron_talon');
  ItemSettings:Apply(neutrals.tiers, 1, 5, 'item_keen_optic');
  --ItemSettings:Apply(neutrals.tiers, 1, 5, 'item_mango_tree');
  ItemSettings:Apply(neutrals.tiers, 1, 5, 'item_ocean_heart');
  --ItemSettings:Apply(neutrals.tiers, 1, 5, 'item_poor_mans_shield');
  ItemSettings:Apply(neutrals.tiers, 1, 5, 'item_royal_jelly');
  ItemSettings:Apply(neutrals.tiers, 1, 5, 'item_trusty_shovel');
  ItemSettings:Apply(neutrals.tiers, 1, 5, 'item_recipe_ironwood_tree');   