local voTypes =
{
	MISC 					=	0,
	LOADOUT					=	1,
	DRAFTING				=	2,
	ENTERINGBATTLE			=	3,
	TAUNT					=	4,
	BEGINNINGBATTLE			=	5,
	MOVE					=	6,
	ATTACK					=	7,
	ORDER					=	8,
	ABILITY					=	9,
	LEVEL					=	10,
	KILL					=	11,
	RIVAL					=	12,
	ALLY					=	13,
	LASTHIT					=	14,
	DENY					=	15,
	ITEM					=	16,
	DEATH					=	17,
	RESPAWN					=	18,
	BOTTLE					=	19,
	RUNE					=	20,
	COOLDOWN				=	21,
	MANA					=	22,
	DAMAGE					=	23,
	SELECT					=	24,
	RESPONSE				=	25,
	WIN						=	26,
	LOSE					=	27,
	LAUGH					=	28,
	THANK					=	29,
	COSMETIC				=	30,
	FAILURE					=	31,
	INTHEBAG				=	32,
}
return voTypes